version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: compose_mqtt
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001